In [1]:
import numpy as np

In [3]:
np.__version__
#np.info untuk melihat dokumentasi sebuah perintah

'1.19.2'

In [4]:
a = [1,2,3,4]
b = [5,6,7,8]

In [5]:
a_array = np.array(a)
b_array = np.array(b)

In [6]:
print(a_array+b_array)

[ 6  8 10 12]


In [18]:
#create matrix 3 row 4
sample = np.ones((4,3))
sample

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#create matrix with 3 row 4 column

sample_matrix = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
print(sample_matrix)

[[ 2  7 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


In [10]:
#create 2D matrix with size 10
sample_matrix2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(sample_matrix2.size)

10


In [19]:
#create 3D matrix with 2 rows 3 column and 3 depth
sample_matrix3 = np.ones((2,3,3))
#sample_matrix3 = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[6,7,8]],[[3,4,1],[4,3,2]]])
print(sample_matrix3)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [21]:
#matrix 2D menggunakan zeros 
test = np.zeros((5,3))
test
for i in test:
    i+=2
test

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [24]:
# create range 0 - 99
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
# create range with start and stop 10 sampai 20-1

x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
# create range with start, stop, step 
# step digunakan untuk increment dari value didalam arange
# jika ada e-01 dari 2.000000e-01 adalah 0.2000000 
x = np.arange(10, 21, 2)
x

array([10, 12, 14, 16, 18, 20])

In [43]:
#linspace start, end, banyak data (size)
#spesifik sesuai dengan banyak nya data
#

np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [28]:
#import random jika tidak ingin menggunakan np.random. agar lebih sederhana dalam penggunaan tools di dalam library
from numpy import random

In [29]:
#uniform random nilai nya hanya dari 0-1
random.rand(5,5)

array([[0.17778973, 0.7222536 , 0.51994895, 0.87582217, 0.58780117],
       [0.60773844, 0.90932433, 0.5715787 , 0.97171191, 0.1780037 ],
       [0.91784935, 0.90014587, 0.26173115, 0.35128763, 0.28559622],
       [0.74652524, 0.11655897, 0.17749237, 0.55360783, 0.69352018],
       [0.65658698, 0.65958785, 0.84765439, 0.2408737 , 0.12847021]])

In [30]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[-0.22407482,  1.42291031, -0.75415523, -0.44038752,  1.27830968],
       [-1.76821882, -0.97102695, -0.31268976,  0.06392625,  1.17946679],
       [ 0.6014387 , -0.19697491,  0.38690433,  0.43063455,  0.82451833],
       [ 0.3977393 ,  0.17555281,  0.42455734, -0.88538823, -0.97495248],
       [ 1.3454915 ,  0.20822773,  0.07853014,  0.30967349, -1.22562947]])

In [31]:
#random dengan batas nilai tertentu
random.randint(10)

9

In [33]:
random.randint(2,10,size=4)

array([3, 2, 5, 3])

In [34]:
#dengan nilai size tipe data tupple. tupple adalah sebuah list dengan nilai yang tidak dapat di ubah (mutable)
random.randint(2,10,size=(4,2,2))

array([[[4, 9],
        [7, 2]],

       [[6, 2],
        [2, 6]],

       [[8, 8],
        [9, 5]],

       [[3, 4],
        [5, 7]]])

In [35]:
# generate 1D contain 5 random integer from 0, 100
random.randint(0,100,size=5)

array([ 2, 98, 55, 21, 53])

In [37]:
# generate 2D with 3 row. each row contain 5 random int from 0 to 100
random.randint(0,100,size=(3,5))

array([[36, 12, 44,  6,  8],
       [85, 56, 62, 34, 14],
       [63, 93, 58, 58,  6]])

In [42]:
# generate 1D array of 30 evenly spaced elements between 1.5 and 5.5
np.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])